name: CapovillaPlugins
version: '${project.version}'
main: br.com.vitorcapovilla.CapovillaPlugins
api-version: '1.19'
authors: [Vitor Capovilla]

commands:
  fake:
    description: Comando para alterar o nome de exibição.
    usage: /<command> [restore|random|<novo_nome>]
    aliases: [ nomefalso, mudarnome ]